application:
  #audience: ${env.AUTH0_AUDIENCE:}
  audience: https://hello-world.example.com
  # client-origin-url: ${env.CLIENT_ORIGIN_URL:}
  client-origin-url: http://localhost:4040

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  # port: ${env.PORT:0}

spring:
  mvc:
    throw-exception-if-no-handler-found: true
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: https://dev-wccgbt6l.us.auth0.com/

  web:
    resources:
      add-mappings: false

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect
      cache:
        region.factory_class: org.redisson.hibernate.RedissonRegionFactory
        use_second_level_cache: true
        use_query_cache: true
        redisson:
          fallback: true
          config: /redisson.yaml
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: rmit
    driverClassName: org.postgresql.Driver

  error:
    include-message: always

  jackson:
    serialization.fail-on-empty-beans: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  redis:
    redisson:
      file: classpath:redisson.yaml
      config: |
        clusterServersConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          failedSlaveReconnectionInterval: 3000
          failedSlaveCheckInterval: 60000
          password: null
          subscriptionsPerConnection: 5
          clientName: null
          loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          slaveConnectionMinimumIdleSize: 24
          slaveConnectionPoolSize: 64
          masterConnectionMinimumIdleSize: 24
          masterConnectionPoolSize: 64
          readMode: "SLAVE"
          subscriptionMode: "SLAVE"
          nodeAddresses:
          - "redis://127.0.0.1:7004"
          - "redis://127.0.0.1:7001"
          - "redis://127.0.0.1:7000"
          scanInterval: 1000
          pingConnectionInterval: 0
          keepAlive: false
          tcpNoDelay: false
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.MarshallingCodec> {}
        transportMode: "NIO"

